#!/usr/bin/env bash
set -euo pipefail

# Same as run_best_pm_teacher_datafree.sh, but enables a server-side
# feature generator for data-free KD.

export FEDCD_PM_TEACHER_DATAFREE_ENABLE="${FEDCD_PM_TEACHER_DATAFREE_ENABLE:-true}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_ENABLE="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_ENABLE:-true}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_NOISE_DIM="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_NOISE_DIM:-128}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_HIDDEN_DIM="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_HIDDEN_DIM:-512}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_LR="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_LR:-0.001}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_STEPS="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_STEPS:-1}"
export FEDCD_PM_TEACHER_DATAFREE_GENERATOR_ANCHOR_WEIGHT="${FEDCD_PM_TEACHER_DATAFREE_GENERATOR_ANCHOR_WEIGHT:-0.1}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/run_best_pm_teacher_datafree.sh"
