#!/usr/bin/env bash
set -euo pipefail

# Best historical FedCD setting + Phase-1 cluster-stat distance-weighted PM-teacher ensemble
# Base reference:
# logs/FedCD/GM_VGG8W224_PM_VGG8W1322_Fext_SmallFExt/pat/NC_20/date_20260222/time_114609

export CONDA_ENV="${CONDA_ENV:-pfllib}"
export GPU_ID="${GPU_ID:-0}"
export DATASET="${DATASET:-Cifar10_pat_nc20}"
export NUM_CLASSES="${NUM_CLASSES:-10}"
export NUM_CLIENTS="${NUM_CLIENTS:-20}"
export JOIN_RATIO="${JOIN_RATIO:-1.0}"
export LOCAL_EPOCHS="${LOCAL_EPOCHS:-2}"
export GLOBAL_ROUNDS="${GLOBAL_ROUNDS:-100}"
export LR="${LR:-0.005}"
export BATCH_SIZE="${BATCH_SIZE:-128}"

export NUM_CLUSTERS="${NUM_CLUSTERS:-5}"
export CLUSTER_THRESHOLD="${CLUSTER_THRESHOLD:-0.1}"
export ADAPTIVE_THRESHOLD="${ADAPTIVE_THRESHOLD:-true}"
export CLUSTER_PERIOD="${CLUSTER_PERIOD:-2}"
export PM_PERIOD="${PM_PERIOD:-1}"
export GLOBAL_PERIOD="${GLOBAL_PERIOD:-2}"
export CLUSTER_SAMPLE_SIZE="${CLUSTER_SAMPLE_SIZE:-512}"
export FEDCD_NC_WEIGHT="${FEDCD_NC_WEIGHT:-0.02}"
export FEDCD_NC_TARGET_CORR="${FEDCD_NC_TARGET_CORR:--0.1}"

export GM_MODEL="${GM_MODEL:-VGG8W224}"
export PM_MODEL="${PM_MODEL:-VGG8W1322}"
export FEXT_MODEL="${FEXT_MODEL:-SmallFExt}"
export FEXT_DIM="${FEXT_DIM:-256}"

export FEDCD_GM_UPDATE_MODE="${FEDCD_GM_UPDATE_MODE:-server_pm_teacher}"
export FEDCD_FUSION_MODE="${FEDCD_FUSION_MODE:-soft}"
export FEDCD_FUSION_WEIGHT="${FEDCD_FUSION_WEIGHT:-0.6}"
export FEDCD_PM_LOGITS_WEIGHT="${FEDCD_PM_LOGITS_WEIGHT:-0.7}"
export FEDCD_PM_ONLY_WEIGHT="${FEDCD_PM_ONLY_WEIGHT:-1.5}"
export FEDCD_GM_LOGITS_WEIGHT="${FEDCD_GM_LOGITS_WEIGHT:-0.0}"
export FEDCD_ENTROPY_MIN_PM_WEIGHT="${FEDCD_ENTROPY_MIN_PM_WEIGHT:-0.8}"
export FEDCD_ENTROPY_MAX_PM_WEIGHT="${FEDCD_ENTROPY_MAX_PM_WEIGHT:-0.98}"
export FEDCD_ENTROPY_GATE_TAU="${FEDCD_ENTROPY_GATE_TAU:-0.1}"
export FEDCD_ENTROPY_PM_BIAS="${FEDCD_ENTROPY_PM_BIAS:-0.05}"
export FEDCD_ENTROPY_GM_BIAS="${FEDCD_ENTROPY_GM_BIAS:-0.0}"
export FEDCD_ENTROPY_DISAGREE_GM_BOOST="${FEDCD_ENTROPY_DISAGREE_GM_BOOST:-0.0}"
export FEDCD_ENTROPY_USE_CLASS_RELIABILITY="${FEDCD_ENTROPY_USE_CLASS_RELIABILITY:-true}"
export FEDCD_ENTROPY_RELIABILITY_SCALE="${FEDCD_ENTROPY_RELIABILITY_SCALE:-0.8}"
export FEDCD_ENTROPY_HARD_SWITCH_MARGIN="${FEDCD_ENTROPY_HARD_SWITCH_MARGIN:-0.2}"
export FEDCD_ENTROPY_USE_OOD_GATE="${FEDCD_ENTROPY_USE_OOD_GATE:-true}"
export FEDCD_ENTROPY_OOD_SCALE="${FEDCD_ENTROPY_OOD_SCALE:-0.5}"
export FEDCD_ENTROPY_OOD_USE_CLASS_STATS="${FEDCD_ENTROPY_OOD_USE_CLASS_STATS:-true}"
export FEDCD_ENTROPY_OOD_CLASS_MIX="${FEDCD_ENTROPY_OOD_CLASS_MIX:-0.6}"

# Keep v2 additions neutral to stay close to the historical best run.
export FEDCD_TASK_FEXT_TRAIN_MODE="${FEDCD_TASK_FEXT_TRAIN_MODE:-frozen}"
export FEDCD_RESIDUAL_MODULE_ENABLE="${FEDCD_RESIDUAL_MODULE_ENABLE:-false}"
export FEDCD_BRANCH_CONSISTENCY_WEIGHT="${FEDCD_BRANCH_CONSISTENCY_WEIGHT:-0.0}"
export FEDCD_RESIDUAL_LOGIT_REG_WEIGHT="${FEDCD_RESIDUAL_LOGIT_REG_WEIGHT:-0.0}"

export TEACHER_PROXY_DATASET="${TEACHER_PROXY_DATASET:-Cifar100}"
export TEACHER_SOURCE="${TEACHER_SOURCE:-cluster}"
export TEACHER_TOPK="${TEACHER_TOPK:-5}"
export TEACHER_ABSTAIN_THRESHOLD="${TEACHER_ABSTAIN_THRESHOLD:-0.3}"
export TEACHER_TEACHER_ABSTAIN_THRESHOLD="${TEACHER_TEACHER_ABSTAIN_THRESHOLD:-0.5}"
export TEACHER_MIN_ACTIVE="${TEACHER_MIN_ACTIVE:-2}"
export TEACHER_CONSENSUS_MIN_RATIO="${TEACHER_CONSENSUS_MIN_RATIO:-0.6}"

export FEDCD_PM_TEACHER_SAMPLES="${FEDCD_PM_TEACHER_SAMPLES:-50000}"
export FEDCD_PM_TEACHER_BATCH_SIZE="${FEDCD_PM_TEACHER_BATCH_SIZE:-256}"
export FEDCD_PM_TEACHER_EPOCHS="${FEDCD_PM_TEACHER_EPOCHS:-6}"
export FEDCD_INIT_EPOCHS="${FEDCD_INIT_EPOCHS:-5}"
export FEDCD_INIT_SAMPLES="${FEDCD_INIT_SAMPLES:-50000}"
export FEDCD_INIT_BATCH_SIZE="${FEDCD_INIT_BATCH_SIZE:-256}"

export FEDCD_PM_TEACHER_COMPETENCE_FILTER="${FEDCD_PM_TEACHER_COMPETENCE_FILTER:-false}"
export FEDCD_PM_TEACHER_CLUSTER_DIST_WEIGHTING="${FEDCD_PM_TEACHER_CLUSTER_DIST_WEIGHTING:-true}"
export FEDCD_PM_TEACHER_CLUSTER_DIST_TAU="${FEDCD_PM_TEACHER_CLUSTER_DIST_TAU:-1.0}"
export FEDCD_PM_TEACHER_CLUSTER_DIST_METRIC="${FEDCD_PM_TEACHER_CLUSTER_DIST_METRIC:-mahalanobis}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/run.sh"
